site_name: Tsukimakura's notebook
theme:
  name: material

  icon:
    logo: material/github

  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: grey
      icon: material/brightness-7 
      name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      icon: material/brightness-4
      name: Switch to light mode

  features:
      - navigation.top # 返回顶部按钮
      - navigation.tabs # 顶部分类标签
      - search.highlight # 搜索结果高亮显示


copyright: Copyright © 2025 Tsukimakura